spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: hhsy
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.111:3306/shanghaigzw-data?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: hhsy
  profiles: dev
  
#打印mybatis的日志  
logging:
  level:
    com.softline.dao: debug
    
mybatis:
  configuration:
    cache-enabled: true    
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    